<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV-Yahya</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>YAHYA ANROUZ</h1>
    </div>
    <h2>Informations personnelles</h2>
    <p>nom et prénom: Anrouz Yahya</p>
    <p>Email :
         yahya.anrouz.62@edu.uiz.ac.ma</p>
    <p>Date de naissance : 10|05|2007</p>
    <h2>FORMATIONS</h2>
    <ul>
        <li>Baccalauréat Sciences Mathématiques B option francais</li>
        <li>édudiant en Faculté polydisciplinaire-OUARZAZATE ,
             licence au securité et réseaux informatiques</li>
    </ul>
    <h2>Compétences</h2>
    <ul>
        <li>capable d'analiser</li>
        <li>adaptation</li>
        <li>python et html (nivau basique 
        )
        </li>
         <h2>expériences</h2>
         <ul>
            <li>travaillieur saisonnier au societé minière d'imiter , 2 fois</li>
         </ul>
         <li>participant aux activités parascolaires</li>
         <li>tournoi de taekwondo local</li>

    </ul>
</body>
</html>
